ITnavigation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('navigation.urls')),
    # path('articles/<year>/<month>/', views.month_archive),
    # path('articles/<year>/<month>/<int:pk>/', views.article_detail),
]

navigation/urls.py
from django.urls import path
from . import views

app_name = 'navigation'
urlpatterns = [
    # path 路径后面要加/ 与1.x的区别
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('pm', views.pm, name='pm'),
    path('ui', views.ui, name='ui'),
    path('cehua', views.cehua, name='cehua'),
    path('blog', views.blog, name='blog'),
    # path('articles/<year>/<month>/', views.month_archive),
    # path('articles/<year>/<month>/<int:pk>/', views.article_detail),
]

navigation/models.py
from django.db import models


# 网站分区选择表
class PartChoice(models.Model):
    part = models.CharField(max_length=30, verbose_name='网站分区')

    class Meta:
        db_table = 'part'
        verbose_name = "0_网站分区"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str("%s" % self.part)


# 网站分组选择表
class GroupChoice(models.Model):
    group_part = models.ForeignKey(PartChoice, on_delete=models.CASCADE)
    group = models.CharField(max_length=30, verbose_name='网站分组')

    class Meta:
        db_table = 'group'
        verbose_name = "1_网站分组"
        verbose_name_plural = verbose_name

    def __str__(self):
        return str("%s-%s" % (self.group_part.part, self.group))


# 网站信息表
class Site(models.Model):
    site_group = models.ForeignKey('GroupChoice', on_delete=models.CASCADE)  # 如果你要关联的模型位于当前模型之后，则需要通过字符串的方式进行引用
    url = models.URLField(verbose_name='网站链接')
    title = models.CharField(max_length=50, verbose_name="网站标题")
    info = models.CharField(max_length=200, blank=True, null=True, verbose_name="网站介绍")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    class Meta:
        db_table = 'site'
        verbose_name = '2_网站信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.url
        return '%s-%s-%s' % (self.site_group.group_part.part, self.site_group.group, self.title)

# null 是从数据库层面，允许为空，如果null==True的话，Django 在数据库中会将空值(empty)存储为 NULL，用SQL来说明就是为该列添加了NOT NULL的约束。默认是False。
# blank 是用于验证。如果一个字段的 blank=True ，Django 在进行表单数据验证时，会允许该字段是空值。如果字段的 blank=False ，该字段就是必填的。

navigation/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import PartChoice, GroupChoice, Site


def index(request):
    all_part = PartChoice.objects.all()
    all_group = GroupChoice.objects.all()
    all_site = Site.objects.all()
    return render(request, 'navigation/index.html', locals())


def pm(request):
    return render(request, 'navigation/pm.html', locals())


def ui(request):
    return render(request, 'navigation/ui.html', locals())


def cehua(request):
    return render(request, 'navigation/cehua.html', locals())


def blog(request):
    return render(request, 'navigation/blog.html', locals())

navigation/templates/navigation/blog.html
{#<!DOCTYPE html>#}
{#<html><head>#}
{#	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">#}
{#	<meta charset="utf-8">#}
{#	<title>编程导航-ITnavigation</title>#}
{#	<meta name="keywords" content="编程导航-ITnavigation">#}
{#    <meta name="description" content="编程导航-ITnavigation">#}
{#	<link rel="shortcut icon" href="files/favicon.ico">#}
{#	<link rel="stylesheet" href="files/bootstrap.css" type="text/css">#}
{#	<link rel="stylesheet" href="files/style.css" type="text/css">	#}
{#<style></style>#}
{#</head>#}
{#<body>#}
{# #}
{#<!--导航栏 begin-->#}
{#<header id="topDiv">#}
{#<nav class="navbar navbar-inverse navbar-fixed-top">#}
{#    <div class="container"> #}
{#      <div class="navbar-header">   #}
{#        <a class="navbar-brand" href="index.html">       	 #}
{#         <img src="logo.png" style="margin-top: -15px;width:120px;height:50px;">        </a>#}
{#        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">#}
{#          <span class="icon-bar"></span>#}
{#          <span class="icon-bar"></span>#}
{#          <span class="icon-bar"></span>#}
{#        </button>#}
{#      </div>#}
{#      <div id="navbar-collapse" class="collapse navbar-collapse">         #}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                <li><a class="active" href="index.html"><span>编程语言</span></a></li>#}
{#            	<li><a href="pm.html" title="产品经理"><span>产品经理</span></a></li>#}
{#                <li><a href="ui.html" title="UI"><span>UI</span></a></li>#}
{#                <li><a href="cehua.html" title="策划"><span>策划</span></a></li>#}
{#                <li class="active"><a href="blog.html" title="博客"><span>博客</span></a></li>                #}
{#                <li style="margin-top:-6px;"> &nbsp; #}
{#                 <form action="http://www.baidu.com/baidu" target="_blank">  #}
{#                  <input name=tn type=HIDDEN value=baidu>  #}
{#                  <a href="http://www.baidu.com/"></a>  #}
{#                  <input id="kw" type="text" class="form-group" placeholder="搜你想搜的" name="word" size="30" baiduSug="1">  #}
{#                   <input type="submit" class="btn-default"value="百度">  #}
{#                 </form></li>#}
{#            </ul>#}
{#        </div>#}
{#     </div>#}
{# </nav>#}
{# </header> #}
{#<!--导航栏 end-->#}
{# #}
{# <div class="container">       #}
{#   <div class="daohan"> #}
{#        	#}
{#       </div> #}
{#</div>#}
{% extends 'base.html' %}
{% load static %}

{% block title %}
    主页
{% endblock %}

{% block content %}

    <div class="container">
        <div class="daohan">

        </div>
    </div>



    <div class="container">
        <div class="container">


            <div class="site-area floor_3">
                <div class="floor">论坛</div>
                <ul>
                    <li class="title"><a href="#" onclick="return false" target="_blank">资讯</a></li>
                    <li><a href="http://www.zhihu.com/" target="_blank">知乎</a></li>
                    <li><a href="http://36kr.com/" target="_blank">36kr</a></li>
                    <li><a href="http://www.9miao.com/" target="_blank">9秒社团</a></li>
                    <li><a href="http://www.infoq.com/cn/" target="_blank">infoq</a></li>
                    <li><a href="https://segmentfault.com/" target="_blank">segment</a></li>
                </ul>

            </div>
            <div class="site-area floor_4">
                <div class="floor">博客</div>
                <ul>
                    <li class="title"><a href="#" onclick="return false" target="_blank">博客</a></li>
                    <li><a href="https://www.cnblogs.com/" target="_blank">博客园</a></li>
                    <li><a href="http://blog.51cto.com/" target="_blank">51博客</a></li>
                </ul>
            </div>


        </div>
    </div>
{% endblock %}

{#<div class="site-bottom container-fluid">#}
{# <center>#}
{#    <p>关于站点</p>	   #}
{#    <p class="info">这是一个我收集的关于编程的一些网站，希望能给自己的学习提供一些帮助，也希望给大家带来更多方便！！如果有好的网站推荐，请联系QQ：<a href="http://wpa.qq.com/msgrd?v=3&uin=2951121599&site=qq&menu=yes" target="_blank" title="QQ号：2951121599">2951121599</a>#}
{#</p>#}
{# </center>        #}
{#</div>#}
{# #}
{#<div style="display: none;" id="goToTop"><a href="javascript:"></a></div>#}
{# #}
{#  <script charset="gbk" src="http://www.baidu.com/js/opensug.js"></script>#}
{##}
{#<script src="files/jquery.js" type="text/javascript"></script> #}
{#<script src="files/style.js" type="text/javascript"></script>#}
{##}
{#</body></html>#}

navigation/templates/navigation/cehua.html
{#<!DOCTYPE html>#}
{#<html><head>#}
{#	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">#}
{#	<meta charset="utf-8">#}
{#	<title>编程导航-ITnavigation</title>#}
{#	<meta name="keywords" content="编程导航-ITnavigation">#}
{#    <meta name="description" content="编程导航-ITnavigation">#}
{#	<link rel="shortcut icon" href="files/favicon.ico">#}
{#	<link rel="stylesheet" href="files/bootstrap.css" type="text/css">#}
{#	<link rel="stylesheet" href="files/style.css" type="text/css">	#}
{#    <style></style>#}
{#</head>#}
{#<body>#}
{# #}
{#<!--导航栏 begin-->#}
{#<header id="topDiv">#}
{#<nav class="navbar navbar-inverse navbar-fixed-top">#}
{#    <div class="container"> #}
{#      <div class="navbar-header">   #}
{#        <a class="navbar-brand" href="index.html">       	 #}
{#         <img src="logo.png" style="margin-top: -15px;width:120px;height:50px;">        </a>#}
{#        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">#}
{#          <span class="icon-bar"></span>#}
{#          <span class="icon-bar"></span>#}
{#          <span class="icon-bar"></span>#}
{#        </button>#}
{#      </div>#}
{#      <div id="navbar-collapse" class="collapse navbar-collapse">         #}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                <li><a class="active" href="index.html"><span>编程语言</span></a></li>#}
{#            	<li><a href="pm.html" title="产品经理"><span>产品经理</span></a></li>#}
{#                <li><a href="ui.html" title="UI"><span>UI</span></a></li>#}
{#                <li class="active"><a href="cehua.html" title="策划"><span>策划</span></a></li>#}
{#                <li><a href="blog.html" title="博客"><span>博客</span></a></li>                #}
{#              <li style="margin-top:-6px;"> &nbsp; #}
{#                 <form action="http://www.baidu.com/baidu" target="_blank">  #}
{#                  <input name=tn type=HIDDEN value=baidu>  #}
{#                  <a href="http://www.baidu.com/"></a>  #}
{#                  <input id="kw" type="text" class="form-group" placeholder="搜你想搜的" name="word" size="30" baiduSug="1">  #}
{#                   <input type="submit" class="btn-default"value="百度">  #}
{#                 </form></li>#}
{#            </ul>#}
{#        </div>#}
{#     </div>#}
{# </nav>#}
{# </header> #}
{#<!--导航栏 end-->#}
{# #}
{# #}
{#<!--二级菜单-end-->#}
{# #}
{#<div class="container ">#}
{#        <div class="daohan">#}
{#        	#}
{#       </div> #}
{#</div>#}
{% extends 'base.html' %}
{% load static %}

{% block title %}
    主页
{% endblock %}

{% block content %}

    <div class="container">
        <div class="daohan">

        </div>
    </div>

    <!-----------游戏策划------------->
    <div class="container">

        <div class="site-area floor_1">
            <div class="floor">游戏资讯</div>
            <ul>
                <li class="title"><a href="#" onclick="return false" target="_blank">直播</a></li>
                <li><a href="http://www.douyutv.com/" target="_blank">斗鱼</a></li>
                <li><a href="http://www.huya.com/" target="_blank">虎牙</a></li>
                <li><a href="http://www.yy.com/" target="_blank">YY直播</a></li>
                <li><a href="" target="_blank"></a></li>
            </ul>
        </div>

        <div class="site-area floor_2">
            <div class="floor">游戏国内公司</div>
            <ul>
                <li class="title"><a href="#" onclick="return false" target="_blank">页游</a></li>
                <li><a href="http://4399.com/" target="_blank">4399</a></li>
                <li><a href="http://wan.yy.com/" target="_blank">yy游戏</a></li>
            </ul>
            <ul>
                <li class="title"><a href="#" onclick="return false" target="_blank">页游</a></li>

                <li><a href="http://www.youzu.com/" target="_blank">游族网络</a></li>
            </ul>


        </div>


        <div class="clear"></div>
    </div>
    <div class="container">
        <!-----------招聘求职------------->
        <div class="site-area floor_1">
            <div class="floor"> 招聘求职</div>
            <ul>
                <li class="title"><a href="#" onclick="return false" target="_blank">求职</a></li>
                <li><a href="http://www.51job.com/" target="_blank">51job</a></li>
                <li><a href="http://www.lagou.com/" target="_blank">拉勾网</a></li>
                <li><a href="http://www.zhaopin.com/" target="_blank">智联招聘</a></li>
                <li><a href="http://www.chinahr.com/dongguan/" target="_blank">中华英才</a></li>
                <li><a href="http://www.100offer.com/" target="_blank">100offer</a></li>
                <li><a href="http://mynews.goodjob.cn/" target="_blank">应届生</a></li>
                <li><a href="http://www.liepin.com/" target="_blank">猎聘网</a></li>
                <li><a href="http://www.shixiseng.com/" target="_blank">实习僧</a></li>
            </ul>

        </div>


    </div>


    </div>
{% endblock %}
{#<div class="site-bottom container-fluid">#}
{# <center>#}
{#    <p>关于站点</p>	   #}
{#    <p class="info">这是一个我收集的关于编程的一些网站，希望能给自己的学习提供一些帮助，也希望给大家带来更多方便！！如果有好的网站推荐，请联系QQ：<a href="http://wpa.qq.com/msgrd?v=3&uin=2951121599&site=qq&menu=yes" target="_blank" title="QQ号：2951121599">2951121599</a>#}
{#</p>#}
{# </center>        #}
{#</div>#}
{# #}
{#<div style="display: none;" id="goToTop"><a href="javascript:"></a></div>#}
{# #}
{#  <script charset="gbk" src="http://www.baidu.com/js/opensug.js"></script>#}
{##}
{#<script src="files/jquery.js" type="text/javascript"></script> #}
{#<script src="files/style.js" type="text/javascript"></script>#}
{##}
{#</body></html>#}

navigation/templates/navigation/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    主页
{% endblock %}

{% block content %}
    <!--内容栏 begin-->
    <div class="container">
        {% for part in all_part %}
            {% if forloop.counter > 10 %}
                <div class="site-area floor_{{ forloop.counter|add:-10 }}">
            {% else %}
                <div class="site-area floor_{{ forloop.counter }}">
            {% endif %}
        <!--编程网站列表-->
        <div class="floor">{{ part }}</div>

        {% for group in all_group %}
            {% ifequal part.id group.group_part_id %}
                <!--次列表-->
                <ul>
                    <li class="title"><a href="#" onclick="return false" target="_blank">{{ group.group }}</a></li>
                    {% for site in all_site %}
                        {% ifequal group.id site.site_group_id %}
                            <li><a href="{{ site.url }}" target="_blank"><b>{{ site.title }}</b></a></li>
                        {% endifequal %}
                    {% endfor %}
                </ul>
            {% endifequal %}
        {% endfor %}
        </div>
        {% endfor %}
        </div>
    </div>
    <!--内容栏 end-->
{% endblock %}

navigation/templates/navigation/pm.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    主页
{% endblock %}

{% block content %}

    <div class="container">
        <div class="daohan">

        </div>
    </div>



    <div class="container">

        <div class="site-area floor_1">

            <div class="floor">用户体验</div>
            <ul>
                <li class="title"><a href="#" onclick="return false" target="_blank">体验</a></li>
                <li><a href="http://isux.tencent.com/" target="_blank">腾讯ISUX</a></li>
                <li><a href="http://cdc.tencent.com/" target="_blank">腾讯CDC</a></li>
                <li><a href="" target="_blank"></a></li>
            </ul>
            <ul>
                <li class="title"><a href="#" onclick="return false" target="_blank">产品</a></li>
                <li><a href="http://www.masterchat.cn/" target="_blank">产品邦</a></li>
                <li><a href="http://www.chanpin100.com/" target="_blank">产品100</a></li>
                <li><a href="http://www.b2cpm.com/" target="_blank">经理王</a></li>
                <li><a href="http://www.woshipm.com/" target="_blank">人人经理</a></li>
                <li><a href="http://www.zhihu.com/question/19563363" target="_blank">产品人责任</a></li>
            </ul>

        </div>


        <div class="site-area floor_2">
            <div class="floor">站长工具</div>
            <ul>
                <li class="title"><a href="#" onclick="return false" target="_blank">站长</a></li>
                <li><a href="http://tool.chinaz.com/" target="_blank">站长之家</a></li>
                <li><a href="" target="_blank"></a></li>
                <li><a href="" target="_blank"></a></li>
                <li><a href="" target="_blank"></a></li>
                <li><a href="" target="_blank"></a></li>
                <li><a href="" target="_blank"></a></li>
                <li><a href="" target="_blank"></a></li>
            </ul>
        </div>

    </div>
{% endblock %}

navigation/templates/navigation/safety.html
<!DOCTYPE html>
<html><head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<title>编程导航-ITnavigation</title>
	<meta name="keywords" content="编程导航-ITnavigation">
    <meta name="description" content="编程导航-ITnavigation">
	<link rel="shortcut icon" href="files/favicon.ico">
	<link rel="stylesheet" href="files/bootstrap.css" type="text/css">
	<link rel="stylesheet" href="files/style.css" type="text/css">	
    <style></style>
</head>
<body>
 
<!--导航栏 begin-->
<header id="topDiv">
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container"> 
      <div class="navbar-header">   
        <a class="navbar-brand" href="index.html">       	 
         <img src="logo.png" style="margin-top: -15px;width:120px;height:50px;">        </a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar-collapse" class="collapse navbar-collapse">         
            <ul class="nav navbar-nav navbar-right">
                <li><a class="active" href="index.html"><span>编程语言</span></a></li>
            	<li><a href="product.html" title="产品经理"><span>产品经理</span></a></li>
                <li><a href="ui.html" title="UI"><span>UI</span></a></li>
                <li><a href="cehua.html" title="策划"><span>策划</span></a></li>
                <li><a href="blog.html" title="博客"><span>博客</span></a></li>                
               <li class="active"> <a href="safety.html" title="安全"><span>安全</span></a></li>
                <li style="margin-top:-6px;"> &nbsp; 
                 <form action="http://www.baidu.com/baidu" target="_blank">  
                  <input name=tn type=HIDDEN value=baidu>  
                  <a href="http://www.baidu.com/"></a>  
                  <input id="kw" type="text" class="form-group" placeholder="搜你想搜的" name="word" size="30" baiduSug="1">  
                   <input type="submit" class="btn-default"value="百度">  
                 </form></li>
            </ul>
        </div>
     </div>
 </nav>
 </header> 
<!--导航栏 end-->

<!--图片栏 begin-->
<div class="container">
        <div class="daohan">
        	
        </div>
</div>
<!--图片栏 end-->






<div class="container">
 
	
</div>

 

 
<div class="site-bottom container-fluid">
 <center>
    <p>关于站点</p>	   
    <p class="info">这是一个我收集的关于编程的一些网站，希望能给自己的学习提供一些帮助，也希望给大家带来更多方便！！如果有好的网站推荐，请联系QQ：<a href="http://wpa.qq.com/msgrd?v=3&uin=2951121599&site=qq&menu=yes" target="_blank" title="QQ号：2951121599">2951121599</a>
</p>
 </center>        
</div>
 
<div style="display: none;" id="goToTop"><a href="javascript:"></a></div>
<script charset="gbk" src="http://www.baidu.com/js/opensug.js"></script>
<script src="files/jquery.js" type="text/javascript"></script> 
<script src="files/style.js" type="text/javascript"></script>

</body></html>

navigation/templates/navigation/sound.html
<!DOCTYPE html>
<html><head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
	<title>编程导航-ITnavigation</title>
	<meta name="keywords" content="编程导航-ITnavigation">
    <meta name="description" content="编程导航-ITnavigation">
	<link rel="shortcut icon" href="files/favicon.ico">	
    <link rel="stylesheet" href="files/bootstrap.css" type="text/css">
	<link rel="stylesheet" href="files/style.css" type="text/css">	
    <style></style>
</head>
<body>
 
<!--导航栏 begin-->
<header id="topDiv">
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container"> 
      <div class="navbar-header">   
        <a class="navbar-brand" href="index.html">       	 
         <img src="logo.png" style="margin-top: -15px;width:120px;height:50px;">        </a>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div id="navbar-collapse" class="collapse navbar-collapse">         
            <ul class="nav navbar-nav navbar-right">
                <li><a class="active" href="index.html"><span>编程语言</span></a></li>
            	<li><a href="product.html" title="产品经理"><span>产品经理</span></a></li>
                <li><a href="ui.html" title="UI"><span>UI</span></a></li>
                <li><a href="cehua.html" title="策划"><span>策划</span></a></li>
                <li><a href="blog.html" title="博客"><span>博客</span></a></li>                
                <li class="active"><a href="sound.html" title="音效素材"><span>音效素材</span></a></li>
                <li><a href="safety.html" title="安全"><span>安全</span></a></li>
               <li style="margin-top:-6px;"> &nbsp; 
                 <form action="http://www.baidu.com/baidu" target="_blank">  
                  <input name=tn type=HIDDEN value=baidu>  
                  <a href="http://www.baidu.com/"></a>  
                  <input id="kw" type="text" class="form-group" placeholder="搜你想搜的" name="word" size="30" baiduSug="1">  
                   <input type="submit" class="btn-default"value="百度">  
                 </form></li>
            </ul>
        </div>
     </div>
 </nav>
 </header> 
<!--导航栏 end-->
 

  <div class="container">
         
      <div class="daohan"> 
        	
        </div>
 
</div>
    
 
 <div class="container">
  
           
           
</div>
           

   

<div class="site-bottom container-fluid">
 <center>
    <p>关于站点</p>	   
    <p class="info">这是一个我收集的关于编程的一些网站，希望能给自己的学习提供一些帮助，也希望给大家带来更多方便！！如果有好的网站推荐，请联系QQ：<a href="http://wpa.qq.com/msgrd?v=3&uin=2951121599&site=qq&menu=yes" target="_blank" title="QQ号：2951121599">2951121599</a>
</p>
 </center>        
</div>
 
<div style="display: none;" id="goToTop"><a href="javascript:"></a></div>
 
  <script charset="gbk" src="http://www.baidu.com/js/opensug.js"></script>

<script src="files/jquery.js" type="text/javascript"></script> 
<script src="files/style.js" type="text/javascript"></script>

</body></html>

templates/head.html
{#<div id="nav">#}
{#    <div class="con">#}
{#        <div class="log">众包网站</div>#}
{#        <ul>#}
{#            <li id="l1"><a href="/" class="focus">网站首页</a></li>#}
{#            <li id="l2"><a href="{% url 'outsource:projects' %}">项目列表</a></li>#}
{#            <li id="l3"><a href="{% url 'outsource:developers' %}">开发者</a></li>#}
{#            <li id="l4"><a href="{% url 'circle:index' %}">技术圈</a></li>#}
{#            <li id="l5"><a href="{% url 'trade:index' %}">项目分享</a></li>#}
{#            <li id="l6"><a href="{% url 'outsource:help' %}">帮助</a>#}
{#                <ul id="sub_nav">#}
{#                    <li><a href="{% url 'outsource:guide1' %}">需求方指南 </a></li>#}
{#                    <li><a href="{% url 'outsource:guide2' %}">开发者指南 </a></li>#}
{#                </ul>#}
{#            </li>#}
{#            <li id="l7"><a href="{% url 'outsource:publish' %}">发布项目</a></li>#}
{#        </ul>#}
{#        <div class="act">#}
{#            {% if request.session.islogin %}#}
{#                <a href="{% url 'user:logout' %}">登出</a>#}
{#                <a href="{% url 'user:user' %}">{{ request.session.username }} 的个人中心</a>#}
{#            {% else %}#}
{#                <a href="{% url 'user:login' %}">登录</a>#}
{#                <a href="{% url 'user:register' %}">注册</a>#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{#</div>#}

{% load static %}
<!--导航栏 begin-->
<header id="topDiv">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'navigation:index' %}">
                    <img src="{% static "images/logo.png" %}" style="margin-top: -15px;width:120px;height:50px;"> </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                </button>
            </div>
            <div id="navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li {% if request.path == '/index' %} class="active" {% endif %} >
                        <a href="{% url 'navigation:index' %}"><span>编程语言</span></a></li>
                    <li {% if request.path == '/pm' %} class="active" {% endif %} >
                        <a href="{% url 'navigation:pm' %}" title="产品经理"><span>产品经理</span></a></li>
                    <li {% if request.path == '/ui' %} class="active" {% endif %} >
                        <a href="{% url 'navigation:ui' %}" title="UI"><span>UI</span></a></li>
                    <li {% if request.path == '/cehua' %} class="active" {% endif %} >
                        <a href="{% url 'navigation:cehua' %}" title="策划"><span>策划</span></a></li>
                    <li {% if request.path == '/blog' %} class="active" {% endif %} >
                        <a href="{% url 'navigation:blog' %}" title="博客"><span>博客</span></a></li>
                    <li style="margin-top:-6px;"> &nbsp;
                        <form action="http://www.baidu.com/baidu" target="_blank">
                            <input name=tn type=HIDDEN value=baidu>
                            <a href="http://www.baidu.com/"></a>
                            <input id="kw" type="text" class="form-group" placeholder="搜你想搜的" name="word" size="30"
                                   baiduSug="1">
                            <input type="submit" class="btn-default" value="百度">
                        </form>
                    </li>

                    <li class="active"><a href="http://127.0.0.1:8000/admin" title="后台管理"><span>后台管理</span></a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<!--导航栏 end-->

<!--图片栏 begin-->
<div class="container">
    <div class="daohan">
        <ul>
            <li><a href="https://www.csdn.net/" title="csdn"><img src="{% static "images/csdn.png" %}"></a></li>
            <li><a href="https://github.com/" title="代码仓Github" target="_blank"><img
                    src="{% static "images/github.png" %}"></a>
            </li>
            <li><a href="https://www.v2ex.com/" title="V2EX" target="_blank"><img src="{% static "images/v2ex.png" %}"></a>
            </li>
            <li><a href="https://nodejs.org/en/" title="nodejs" target="_blank"><img
                    src="{% static "images/node.png" %}"></a></li>
            <li><a href="http://www.tiobe.com/tiobe_index?page=index" title="语言流行分布统计" target="_blank"><img
                    src="{% static "images/yuyin.png" %}"></a></li>
            <li><a href="https://www.imooc.com/" title="慕课网" target="_blank"><img src="{% static "images/mooc.png" %}"></a>
            </li>
            <li><a href="http://cn.vuejs.org/" title="vuejs"><img src="{% static "images/vue.png" %}"></a></li>
            <li><a href="https://www.oschina.net/" title="开源中国" target="_blank"><img
                    src="{% static "images/kyzg.png" %}"></a></li>
        </ul>
    </div>
</div>
<!--图片栏 end-->